config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :workers
  resources :settings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
  validates :namespace, uniqueness: true, presence: true

  def to_s
    self.namespace
  end

  def self.get_value(namespace)
    s = Setting.find_by_namespace(namespace)
    if s.present?
      return s.value['value']
    end
    ''
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :cache_globals_settings

  def cache_globals_settings
    @company_name = Setting.get_value('company_name')
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  def index
    @q = Customer.all.ransack(params[:q])
    @customers = @q.result.page(params[:page])
  end

  # GET /customers/1
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer, notice: 'Customer foi criado com sucesso'
    else
      render :new
    end
  end

  # PATCH/PUT /customers/1
  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /customers/1
  def destroy
    @customer.destroy
    redirect_to customers_url, notice: 'Customer foi apagado com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def customer_params
      params.require(:customer).permit(:name, :category, :document_id, :since, :code, :birthdate)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  def index
    @q = Setting.all.ransack(params[:q])
    @settings = @q.result.page(params[:page])
  end

  # GET /settings/1
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      redirect_to @setting, notice: 'Setting foi criado com sucesso'
    else
      render :new
    end
  end

  # PATCH/PUT /settings/1
  def update
    if @setting.update(setting_params)
      redirect_to @setting, notice: 'Setting foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /settings/1
  def destroy
    @setting.destroy
    redirect_to settings_url, notice: 'Setting foi apagado com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def setting_params
      params.require(:setting).permit(:namespace, :value)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  def index
    @q = Worker.all.ransack(params[:q])
    @workers = @q.result.page(params[:page])
  end

  # GET /workers/1
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  def create
    @worker = Worker.new(worker_params)

    if @worker.save
      redirect_to @worker, notice: 'Worker foi criado com sucesso'
    else
      render :new
    end
  end

  # PATCH/PUT /workers/1
  def update
    if @worker.update(worker_params)
      redirect_to @worker, notice: 'Worker foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /workers/1
  def destroy
    @worker.destroy
    redirect_to workers_url, notice: 'Worker foi apagado com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def worker_params
      params.require(:worker).permit(:name, :photo, :document_id, :categories)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5><%= t('errors.template.header')  %>:</h5>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">

    <%= f.label :name %>
    <%= f.text_field :name %>
    
  </div>

  <div class="input-field">

    <%= f.label :category %>
    <%= f.text_field :category %>
    
  </div>

  <div class="input-field">

    <%= f.label :document_id %>
    <%= f.text_field :document_id %>
    
  </div>

  <div class="input-field">

    <%= f.label :since %>
    <%= f.date_select :since %>
    
  </div>

  <div class="input-field">

    <%= f.label :code %>
    <%= f.text_field :code %>
    
  </div>

  <div class="input-field">

    <%= f.label :birthdate %>
    <%= f.date_select :birthdate %>
    
  </div>

</div>
  <div class="actions">
    <%= f.submit t('button.save'), class:"btn" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.customer') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.customer') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.edit') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), customers_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', customer: @customer %>

app/views/customers/index.html.erb
<div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
			<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
				<!-- Search for small screen-->
				<div class="container">
					<div class="row">
						<div class="col s10 m6 l6">
							<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.customers') %></span></h5>
							<ol class="breadcrumbs mb-0">
								<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
								</li>
								<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.customers') %></a>
								</li>
								<li class="breadcrumb-item active"><%= t('breadcrumb.list') %>
								</li>
							</ol>
						</div>
						<div class="col s2 m6 l6"><a class="btn waves-effect waves-light breadcrumbs-btn right border-round" href="<%= new_customer_path %>"><i class="material-icons hide-on-med-and-up">add</i><span class="hide-on-small-only"><%= t "add"  %> <%= t('activerecord.models.customer') %></span></a>
						</div>
					</div>
				</div>
			</div>

<section class="invoice-list-wrapper section">
  <!-- create invoice button-->
  <!-- Options and filter dropdown button-->
  <div class="invoice-filter-action mr-3">
    <div class="row">
    <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
      <div class="col s9 m11">
          <%= f.search_field :name_cont, placeholder: t('placeholder.search'), class: "search-ransack" %>     
      </div>
      <div class="col s3 m1">
				<button type="submit" class="btn-floating mb-1 waves-effect waves-light rigth">
					<i class="material-icons">search</i>
				</button>
      </div>
    <% end %>
    </div>
  </div>
  <p></p>
  <!-- create invoice button-->
  <div class="responsive-table">
    <style>td{padding: 15px}</style>
    <table class="table invoice-data-table white border-radius-4 pt-1">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.customer.name') %></th>
          <th><%= t('activerecord.attributes.customer.category') %></th>
          <th><%= t('activerecord.attributes.customer.document_id') %></th>
          <th><%= t('activerecord.attributes.customer.since') %></th>
          <th><%= t('activerecord.attributes.customer.code') %></th>
          <th><%= t('activerecord.attributes.customer.birthdate') %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
            <td><%= customer.name %></td>
            <td><%= customer.category %></td>
            <td><%= customer.document_id %></td>
            <td><%= customer.since %></td>
            <td><%= customer.code %></td>
            <td><%= customer.birthdate %></td>
          <td>
            <div class="invoice-action right-align">
              <%= link_to customer, class: "invoice-action-view mr-4" do %>
                <i class="material-icons">remove_red_eye</i>
              <% end %>
              <%= link_to edit_customer_path(customer) , class: "invoice-action-edit mr-4" do %>
                <i class="material-icons">edit</i>
              <% end %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate(@customers)  %>
</section>

app/views/customers/new.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.customer') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.customer') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.new') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), customers_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
  <!-- Search for small screen-->
  <div class="container">
    <div class="row">
      <div class="col s10 m6 l6">
        <h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.customer') %></span></h5>
        <ol class="breadcrumbs mb-0">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
          </li>
          <li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.customer') %></a>
          </li>
          <li class="breadcrumb-item active"><%= t('breadcrumb.show') %>
          </li>
        </ol>
      </div>
      <div class="col s2 m6 l6">
        <%= link_to t('button.all'), customers_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
        <%= link_to edit_customer_path(@customer) , class: "btn-flat waves-effect waves-light breadcrumbs-btn right" do %>
          <i class="material-icons">edit</i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card-panel">
	
  <p>
    <strong>Name:</strong>
    <%= @customer.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @customer.category %>
  </p>

  <p>
    <strong>Document:</strong>
    <%= @customer.document_id %>
  </p>

  <p>
    <strong>Since:</strong>
    <%= @customer.since %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= @customer.code %>
  </p>

  <p>
    <strong>Birthdate:</strong>
    <%= @customer.birthdate %>
  </p>

</div>

app/views/layouts/_floating.html.erb
<div style="bottom: 50px; right: 19px;" class="fixed-action-btn direction-top"><a class="btn-floating btn-large gradient-45deg-light-blue-cyan gradient-shadow"><i class="material-icons">add</i></a>
  <ul>
    <li><a href="css-helpers.html" class="btn-floating blue"><i class="material-icons">help_outline</i></a></li>
    <li><a href="cards-extended.html" class="btn-floating green"><i class="material-icons">widgets</i></a></li>
    <li><a href="app-calendar.html" class="btn-floating amber"><i class="material-icons">today</i></a></li>
    <li><a href="app-email.html" class="btn-floating red"><i class="material-icons">mail_outline</i></a></li>
  </ul>
</div>

app/views/layouts/_navside.html.erb
<aside class="sidenav-main nav-expanded nav-lock nav-collapsible sidenav-light sidenav-active-square">
  <div class="brand-sidebar">
    <h1 class="logo-wrapper"><a class="brand-logo darken-1" href="/"><img class="hide-on-med-and-down" src="/materialize/images/logo/materialize-logo-color.png" alt="materialize logo" /><img class="show-on-medium-and-down hide-on-med-and-up" src="/materialize/images/logo/materialize-logo.png" alt="materialize logo" /><span class="logo-text hide-on-med-and-down"><%= @company_name %></span></a><a class="navbar-toggler" href="#"><i class="material-icons">radio_button_checked</i></a></h1>
  </div>
  <ul class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow" id="slide-out" data-menu="menu-navigation" data-collapsible="menu-accordion"></ul>
  <div class="navigation-background"></div><a class="sidenav-trigger btn-sidenav-toggle btn-floating btn-medium waves-effect waves-light hide-on-large-only" href="#" data-target="slide-out"><i class="material-icons">menu</i></a>
</aside>

app/views/layouts/_right_navside.html.erb
<aside id="right-sidebar-nav">
  <div id="slide-out-right" class="slide-out-right-sidenav sidenav rightside-navigation">
    <div class="row">
      <div class="slide-out-right-title">
      </div>
    </div>
  </div>
</aside>

app/views/settings/_form.html.erb
<%= form_for(setting) do |f| %>
  <% if setting.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5><%= t('errors.template.header')  %>:</h5>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">

    <%= f.label :namespace %>
    <%= f.text_field :namespace %>
    
  </div>

  <div class="input-field">

    <%= f.label :value %>
    <%= f.text_area :value %>
    
  </div>

</div>
  <div class="actions">
    <%= f.submit t('button.save'), class:"btn" %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.setting') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.setting') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.edit') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), settings_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', setting: @setting %>

app/views/settings/index.html.erb
<section class="invoice-list-wrapper section">
  <!-- create invoice button-->
  <!-- Options and filter dropdown button-->
  <div class="invoice-filter-action mr-3">
    <div class="row">
      <div class="col s9 m11">
        <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
          <%= f.search_field :namespace_cont, placeholder: t('placeholder.search'), class: "search-ransack" %>
        <% end %>
      </div>
      <div class="col s3 m1">
        <%= link_to new_setting_path, class:"btn-floating mb-1 waves-effect waves-light rigth" do %>
          <i class="material-icons">add</i>
        <% end %>
      </div>
    </div>
  </div>
  <p></p>
  <!-- create invoice button-->
  <div class="responsive-table">
    <style>td{padding: 15px}</style>
    <table class="table invoice-data-table white border-radius-4 pt-1">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.setting.namespace') %></th>
          <th><%= t('activerecord.attributes.setting.value') %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @settings.each do |setting| %>
        <tr>
            <td><%= setting.namespace %></td>
            <td><%= setting.value %></td>
          <td>
            <div class="invoice-action right-align">
              <%= link_to setting, class: "invoice-action-view mr-4" do %>
                <i class="material-icons">remove_red_eye</i>
              <% end %>
              <%= link_to edit_setting_path(setting) , class: "invoice-action-edit mr-4" do %>
                <i class="material-icons">edit</i>
              <% end %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate(@settings)  %>
</section>

app/views/settings/new.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.setting') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.setting') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.new') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), settings_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', setting: @setting %>

app/views/settings/show.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
  <!-- Search for small screen-->
  <div class="container">
    <div class="row">
      <div class="col s10 m6 l6">
        <h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.setting') %></span></h5>
        <ol class="breadcrumbs mb-0">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
          </li>
          <li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.setting') %></a>
          </li>
          <li class="breadcrumb-item active"><%= t('breadcrumb.show') %>
          </li>
        </ol>
      </div>
      <div class="col s2 m6 l6">
        <%= link_to t('button.all'), settings_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
        <%= link_to edit_setting_path(@setting) , class: "btn-flat waves-effect waves-light breadcrumbs-btn right" do %>
          <i class="material-icons">edit</i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card-panel">
	
  <p>
    <strong>Namespace:</strong>
    <%= @setting.namespace %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= @setting.value %>
  </p>

</div>

app/views/workers/_form.html.erb
<%= form_for(worker) do |f| %>
  <% if worker.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5><%= t('errors.template.header')  %>:</h5>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">

    <%= f.label :name %>
    <%= f.text_field :name %>
    
  </div>

  <div class="input-field">

    <%= f.label :photo %>
    <%= f.text_area :photo %>
    
  </div>

  <div class="input-field">

    <%= f.label :document_id %>
    <%= f.text_field :document_id %>
    
  </div>

  <div class="input-field">

    <%= f.label :categories %>
    <%= f.text_field :categories %>
    
  </div>

</div>
  <div class="actions">
    <%= f.submit t('button.save'), class:"btn" %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.worker') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.worker') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.edit') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), workers_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', worker: @worker %>

app/views/workers/index.html.erb
<div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
			<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
				<!-- Search for small screen-->
				<div class="container">
					<div class="row">
						<div class="col s10 m6 l6">
							<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.workers') %></span></h5>
							<ol class="breadcrumbs mb-0">
								<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
								</li>
								<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.workers') %></a>
								</li>
								<li class="breadcrumb-item active"><%= t('breadcrumb.list') %>
								</li>
							</ol>
						</div>
						<div class="col s2 m6 l6"><a class="btn waves-effect waves-light breadcrumbs-btn right border-round" href="new_worker_path"><i class="material-icons hide-on-med-and-up">add</i><span class="hide-on-small-only"><%= t "add"  %> <%= t('activerecord.models.workers') %></span></a>
						</div>
					</div>
				</div>
			</div>
<section class="invoice-list-wrapper section">
  <!-- create invoice button-->
  <!-- Options and filter dropdown button-->
  <div class="invoice-filter-action mr-3">
    <div class="row">
    <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
      <div class="col s9 m11">
          <%= f.search_field :name_cont, placeholder: t('placeholder.search'), class: "search-ransack" %>     
      </div>
      <div class="col s3 m1">
        <button type="submit" class="btn-floating mb-1 waves-effect waves-light rigth">
          <i class="material-icons">search</i>
        </button>

      </div>
    <% end %>
    </div>
  </div>
  <p></p>
  <!-- create invoice button-->
  <div class="responsive-table">
    <style>td{padding: 15px}</style>
    <table class="table invoice-data-table white border-radius-4 pt-1">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.worker.name') %></th>
          <th><%= t('activerecord.attributes.worker.photo') %></th>
          <th><%= t('activerecord.attributes.worker.document_id') %></th>
          <th><%= t('activerecord.attributes.worker.categories') %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @workers.each do |worker| %>
        <tr>
            <td><%= worker.name %></td>
            <td><%= worker.photo %></td>
            <td><%= worker.document_id %></td>
            <td><%= worker.categories %></td>
          <td>
            <div class="invoice-action right-align">
              <%= link_to worker, class: "invoice-action-view mr-4" do %>
                <i class="material-icons">remove_red_eye</i>
              <% end %>
              <%= link_to edit_worker_path(worker) , class: "invoice-action-edit mr-4" do %>
                <i class="material-icons">edit</i>
              <% end %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate(@workers)  %>
</section>

app/views/workers/new.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
	<!-- Search for small screen-->
	<div class="container">
		<div class="row">
			<div class="col s10 m6 l6">
				<h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.worker') %></span></h5>
				<ol class="breadcrumbs mb-0">
					<li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
					</li>
					<li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.worker') %></a>
					</li>
					<li class="breadcrumb-item active"><%= t('breadcrumb.new') %>
					</li>
				</ol>
			</div>
			<div class="col s2 m6 l6">
				<%= link_to t('button.all'), workers_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
			</div>
		</div>
	</div>
</div>

<%= render 'form', worker: @worker %>

app/views/workers/show.html.erb
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
  <!-- Search for small screen-->
  <div class="container">
    <div class="row">
      <div class="col s10 m6 l6">
        <h5 class="breadcrumbs-title mt-0 mb-0"><span><%= t('activerecord.models.worker') %></span></h5>
        <ol class="breadcrumbs mb-0">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a>
          </li>
          <li class="breadcrumb-item"><a href="#"><%= t('activerecord.models.worker') %></a>
          </li>
          <li class="breadcrumb-item active"><%= t('breadcrumb.show') %>
          </li>
        </ol>
      </div>
      <div class="col s2 m6 l6">
        <%= link_to t('button.all'), workers_path, class:"btn waves-effect waves-light breadcrumbs-btn right" %>
        <%= link_to edit_worker_path(@worker) , class: "btn-flat waves-effect waves-light breadcrumbs-btn right" do %>
          <i class="material-icons">edit</i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card-panel">
	
  <p>
    <strong>Name:</strong>
    <%= @worker.name %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= @worker.photo %>
  </p>

  <p>
    <strong>Document:</strong>
    <%= @worker.document_id %>
  </p>

  <p>
    <strong>Categories:</strong>
    <%= @worker.categories %>
  </p>

</div>